global:
  scrape_interval: 15s # How frequently to scrape targets by default
  evaluation_interval: 15s # How frequently to evaluate rules
alerting:
  alertmanagers:
    - static_configs:
      - targets: []
    - timeout: "10s"
      api_version: v2
      path_prefix: /
      scheme: http
      follow_redirects: true
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus server itself

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100'] # Assuming your node exporter is running on the same Docker network as Prometheus

  - job_name: 'sonarqube'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['sonarqube:9000'] # Assuming SonarQube is running on the same Docker network as Prometheus
  
  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']      
