server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - backend
    labels:
      job: varlogs
      __path__: /var/log/**/*.log

- job_name: spring-boot
  static_configs:
  - targets:
        - backend
    labels:
      job: spring-boot
      __path__: /var/log/spring-boot/*.log
