version: '3.9'
services:
  jenkins:
    build: ./jenkins
    container_name: jenkins
    restart: always
    working_dir: /var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - backend-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - backend-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend-network
    depends_on:
      - sonarqube
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - backend-network

  sonarqube:
    image: sonarqube:9.9.5-community
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"
      - "9092:9092"
      - "9093:9093"
    volumes:
      - sonarqube_data:/opt/sonarqube
    networks:
      - backend-network
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data:rw
    networks:
      - backend-network 
  loki:
   image: grafana/loki:2.8.2
   container_name: loki
   ports:
    - "3100:3100"
   command: -config.file=/etc/loki/local-config.yaml
   volumes:
    
      - loki-data:/loki 
   networks:
      - backend-network

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./loki/promtail/promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    restart: always
    ports:
      - "9080:9080"
  
    networks:
      - backend-network 
    
  
networks:
  backend-network:
    external: true
   

volumes:
  jenkins_home:
  grafana_data:
  prometheus_config:
  prometheus_data:
  sonarqube_data:
  nexus-data:
  loki-data:  
